### PR TITLE
Added spotless code formatter

### PR DESCRIPTION
**Pull request by BrownGenius**
https://docs.wpilib.org/en/stable/docs/software/advanced-gradlerio/code-formatting.htmlSpotless

Spotless seems to be the "standard" code formatter for WPILib Java and appears to be the same as Google.  wpiformat seems to be for C++.  This commit just enables running:

./gradlew spotlessCheck - will check modified files and report diffs of formatting suggestions
./gradlew spotlessApply - applies formatting to all files in project (let's avoid this)

Eventually, we can add the "spotlessCheck" as part of the pull_request and get rid of reviewdog/checkstyle etc.

### CODE REVIEW

**Comment by ParkerMeyers** [comment]
@BrownGenius , the robot build failed because of the spotless check, could you check that out? Otherwise I like the idea of using this, just make sure everything builds correctly and Gradle is changed

**Comment by BrownGenius** [comment]
It looks like the gradle build runs the spotless check as part of it and fails as a result: https://github.com/BHSRobotix/ChargedUp2023/actions/runs/3975796765/jobs/6815880906#step:6:33

I'll see if I can make it an informative check, instead of failing the build.

**Comment by ParkerMeyers** [comment]
@BrownGenius It still seems to be failing, if that is on purpose and it will be fine on the main branch, then we can merge, but make sure that it can build.

**Review by ParkerMeyers — APPROVED** [review]

**Comment by BrownGenius** [comment]
@ParkerMeyers No, it's not on purpose. I don't want style failures to prevent checking. I forked the repo to my personal GitHub and am experimenting there so that I don't create too much noise in the bhsrobotix repo. My plan is to integrate reviewdog with spotless and get rid of check style. I'll get it resolved soon.

**Pull request closed without merging**
