### PR TITLE
Joystick fix

### PR DESCRIPTION
**Pull request by rohit18-cool**

### CODE REVIEW

**Review by BrownGenius — APPROVED** [review]
I had to make one minor fix.  The "joystick disconnected" message should be outside of the block where the buttons are assigned.

**Comment by loafdog** [comment]
I forgot to mention few things:
- testing cmds 2nd time last night, the armMoveDistance on right 4 did not work.  It did work first time.  Need to double check this Friday
- we did not test/adjust the distance in armMoveDistance on right 4 to see if it was enough/correct.  Need to test/adjust this value.
- Adi said he did not need PickupFromGround command bound to any button.

**Comment by BrownGenius** [comment]
In #120, I fixed some logic in the ArmMoveDistance.  In simulation, I noticed that the arm didn't move sometimes when "ArmToDistance" was clicked.  If the arm was at the top/bottom limit switch, the command exited immediately.  I fixed it by checking bottomLimit only if moving down, and the topLimit only if moving up.

**Comment by BrownGenius** [comment]
> * Adi said he did not need PickupFromGround command bound to any button.

I'm surprised he doesn't want this.  It will grip, move back (to free the arm if stuck) and moves the arm to a safe driving height.  I'll talk with him Friday more about this.

**Pull request merged**
